apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: postgres1-tcproute
  namespace: default
spec:
  parentRefs:
  - name: eg-postgres1
    namespace: default
    sectionName: tls-terminate-postgres1
  rules:
  - backendRefs:
    - name: postgres1
      port: 5432
      weight: 100
